### ISSUE TITLE
importing from different directories

### ISSUE THREAD

**Issue by c1887** [PhilippsCat/MarkovChains#2]
Hey folks, 

if I want to write a unittest (in whatever framework), I have to start with something where I have to import our class, but I don't know how to do that from a different directory. What I mean is, if I have some testfile located in `tests/`, how can I import from `modules`. What I googled so far suggests to create packages, that is there should be some `__init__.py` files.

**Comment by nbbl** [comment]
Look into the [documentation](https://docs.python.org/2/tutorial/modules.html#packages). When you structure the code like there and use an empty `__init__.py` and use the described `import` commands, it might quite likely work.

**Comment by nbbl** [comment]
Ok, this wasn't as easy as I thought. I just pushed a commit to master (hope you don't mind) with some first tests. You can test the tests by running `nosetests` inside the toplevel `markovchains` folder. If you want to add your own tests you could use my test module as guideline. Please also name your testing functions and modules correspondingly as nosetools automatically detects tests by looking for the keyword "test".

edit: I noticed that I called my repo folder `markovchains` but yours may be called `MarkovChains` and then testing like decribed above wouldn't work. To be independent of the naming of the repo folder I added another level: now you can test with `nosetests` inside of `markov`.
